name: Hocon

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set gradlew permission
        run: chmod +x ./gradlew
      - name: Gradle Clean
        run: ./gradlew clean
      - name: Gradle Build
        run: ./gradlew build
      - name: Packages Publish
        run: ./gradlew publish
