name: Hocon

on: [ push ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '8'
      - name: Set gradlew permission
        run: chmod +x ./gradlew
      - name: Gradle Clean
        run: ./gradlew clean
      - name: Gradle Build
        run: ./gradlew build
      - name: Packages Publish
        run: ./gradlew publish
